const fs = require('fs');
const targetPath = 'c:/Users/blake/Documents/GitHub/trades-hall-omni-twin/packages/physics-solvers/src/qubo.ts';
const lines = [];
function L(...args) { for (const a of args) lines.push(a); }
L('/**');
L(' * PS-3: QUBO, Ising, and Potts Spin Glass Models');
L(' *');
L(' * Builds Quadratic Unconstrained Binary Optimization (QUBO) matrices for');
L(' * event scheduling, converts between QUBO and Ising formulations,');
L(' * implements Potts model construction, and provides SA/PT solver wrappers.');
L(' */');
L('');
L('import type {');
L('  QUBOMatrix, IsingModel, PottsModel,');
L('  EventSpec, RoomSpec, TimeslotSpec, SAConfig, PTConfig,');
L('  PRNG,');
L("} from './types.js'");
L("import { CoolingSchedule, createPRNG } from './types.js'");
L('');
L("import { simulatedAnnealing } from './sa.js'");
L("import { parallelTempering } from './parallel-tempering.js'");
L('');
L('// ---------------------------------------------------------------------------');
L('// Upper-triangular storage helpers');
L('// ---------------------------------------------------------------------------');
L('');
L('/**');
L(' * Index into the flattened upper-triangular array for element (i, j).');
L(' * Canonicalizes so that lo <= hi. Storage order: row-major upper triangle');
L(' * including diagonal.');
L(' *');
L(' *   idx(lo, hi, n) = lo * (2*n - lo - 1) / 2 + hi');
L(' *');
L(' * Total entries: n*(n+1)/2');
L(' */');
L('function upperTriIndex(n: number, i: number, j: number): number {');
L('  const lo = Math.min(i, j)');
L('  const hi = Math.max(i, j)');
L('  return (lo * (2 * n - lo - 1)) / 2 + hi');
L('}');
L('');
L('/**');
L(' * Get the value of Q[i][j] from upper-triangular QUBO storage.');
L(' * Handles both (i,j) and (j,i) by canonicalizing to lo<=hi.');
L(' */');
L('export function getQuboEntry(qubo: QUBOMatrix, i: number, j: number): number {');
L('  const idx = upperTriIndex(qubo.n, i, j)');
L('  return qubo.data[idx] ?? 0');
L('}');
L('');
L('/**');
L(' * Set the value of Q[i][j] in upper-triangular QUBO storage.');
L(' * Handles both (i,j) and (j,i) by canonicalizing to lo<=hi.');
L(' */');
L('export function setQuboEntry(qubo: QUBOMatrix, i: number, j: number, val: number): void {');
L('  const idx = upperTriIndex(qubo.n, i, j)');
L('  qubo.data[idx] = val');
L('}');
L('');
L('/**');
L(' * Add a value to Q[i][j] (accumulate). Canonicalizes to upper-triangular.');
L(' */');
L('function addQuboEntry(qubo: QUBOMatrix, i: number, j: number, val: number): void {');
L('  const idx = upperTriIndex(qubo.n, i, j)');
L('  qubo.data[idx] = (qubo.data[idx] ?? 0) + val');
L('}');
const out = lines.join('\n') + '\n';
fs.writeFileSync(targetPath, out, 'utf8');
console.log('Part 1 written:', out.length, 'bytes');